version: "3"

services:
  flarum:
    build: .
    container_name: flarum
    env_file:
      - .env
    volumes:
      - /Users/khuongdv/Desktop/flarum3/assets:/flarum/app/public/assets
      - /Users/khuongdv/Desktop/flarum3/extensions:/flarum/app/extensions
      - /Users/khuongdv/Desktop/flarum3/storage/logs:/flarum/app/storage/logs
      - /Users/khuongdv/Desktop/flarum3/nginx:/etc/nginx/flarum
    ports:
      - 80:8888
    depends_on:
      - mysql
    networks:
      - flarum-network

  mysql:
    container_name: db
    image: mysql:8.0
    command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: '${DB_NAME}'
      MYSQL_USER: '${DB_USER}'
      MYSQL_PASSWORD: '${DB_PASS}'
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - '3306:3306'
    volumes:
      - './mysql/db/data:/var/lib/mysql'
    networks:
      - flarum-network
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-p${DB_PASS}" ]
      retries: 3
      timeout: 5s

  phpmyadmin:
    depends_on:
      - mysql
    image: phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: '${DB_PASS}'
    networks:
      - flarum-network
networks:
  flarum-network:
    driver: bridge
volumes:
  mysql:
    driver: local
  redis:
    driver: local
