version: "3"

services:
  flarum:
    build: .
    container_name: flarum
    env_file:
      - .env
    volumes:
      - ./flarum-data/assets:/flarum/app/public/assets
      - ./flarum-data/extensions:/flarum/app/extensions
      - ./flarum-data/storage/logs:/flarum/app/storage/logs
      - ./flarum-data/nginx:/etc/nginx/flarum
    ports:
      - 8888:80
networks:
  flarum-network:
    driver: bridge
volumes:
  mysql:
    driver: local
  redis:
    driver: local
